# __Tensor__

## __1.Tensor Structure__
- Tensor
    - data
    - dtype
    - shape
    - device (cpu / cuda)
    - requires_grad

Tensor을 생성하고 구조의 속성을 확인해보자.

`torch.tensor([list])` 형태로 생성한다.

In [ ]:
import torch

x = torch.tensor([1.0, 2.0, 3.0])

print(x.shape)
print(x.dtype)
print(x.device)
print(x.requires_grad)

torch.Size([3])
torch.float32
cpu
False


## __2.Tensor create__


In [ ]:
x = torch.tensor([1,2,3])
y = torch.zeros(2,3)
z = torch.ones(2,3)
w = torch.randn(2,3) 
#rand -> 0~1 균등분포
#randn -> 정규분포

print(x)
print(y)
print(z)
print(w)

tensor([1, 2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 2.1495, -1.5206,  0.1861],
        [-1.7267, -0.0393, -0.2448]])


## __3.Tensor 연산__

- (1)Tensor 연산은 새로운 Tensor 생성한다.
- `(2)inplace 연산`
    - inplace 연산은 a += b와 같은것을 의미한다. Tensor에서도, a.add_(b)와 같은 연산식이 존재한다. 이때 inplace연산시 기존 Tensor 메모리를 직접 수정한다. 예를들어 아래 예시에서, x, y, z 는 다른 tensor로 새로운 메모리에 저장된다. 그러나 inplace연산시 새로운 메모리에 할당하는것이 아닌, 메모리에 저장된 값을 변경하여 추후에 gradient 계산시 문제가 생길수 있다.

In [ ]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
z = x + y

print(z)

tensor([4, 6])
tensor([4, 6])


## __4.requires_grad__

- (1)tensor을 생성하고 gradient 계산 대상을 지정해준다.
    - requires_grad = True 변경 순간, 연산이 기록되고 computational graph가 생성된다.

- (2)computational graph : 연산들의 연결 구조로 계산 흐름을 그래프로 표현한 것이다. 예를들어, 
```python
x = 2
y = x * 3
z = y + 1
```
계산한다고 가정하자. 이는 그냥 계산시 z = (x * 3) + 1 로 연산이 된다.
그러나 그래프(Tree)로 계산시 노드와 연산으로 그릴수 있다. 이 기능은 `backward` 계산시 사용된다.
`이때 backward 계산시 메모리 절약을 위해 그래프는 삭제된다`

In [ ]:
x = torch.tensor([1.0, 2.0], requires_grad = True)