# pytorch package

#### 1. torch

include tensor(like numpy), math function

#### 2. torch.nn

structure neural network.

    - nn.Linear, nn.Conv2d, nn.Module, nn.Relu
    
#### 3. torch.optim

control optimizer(update weight)

    - optim.SGD, optim.Adam
    
#### 4. torch.itils.data

control data(mini_batch, shuffle)

    - Dataset, DataLoader

#### 5. torchvision

control image

    -transforms, datasets.DIFAR10, models.resnet18
    
---
    









# Tensor

Tensor is structure like numpy array. 

But main difference tensor - ndarray is GPU.

#### (1) lets make array with tensor

    torch.tensor



In [1]:
import torch
import numpy as np

data = [[1,2], [3,4]]
x_data = torch.tensor(data)

print(x_data)

tensor([[1, 2],
        [3, 4]])


* it can change ndarray - tensor

In [5]:
x_data = np.array(x_data)
print(x_data)
x_data = torch.tensor(x_data)
print(x_data)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


/var/folders/vf/d0gygbv5527dd2h9xypg_1zm0000gn/T/ipykernel_12027/3643788249.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  x_data = np.array(x_data)


In [6]:
shape = (2, 3)
ones_tensor = torch.ones(shape)
rands_tensor = torch.rand(shape)
zeros_tensor = torch.zeros(shape)
print(ones_tensor)
print(rands_tensor)
print(zeros_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.9045, 0.5621, 0.9300],
        [0.8681, 0.3183, 0.6190]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### (2) Operation

In [ ]:
first_row = ones_tensor[0]
first_col =ones_tensor[:, 0]
last_col = ones_tensor[:, -1]
print(first_row)
print(first_col)
print(last_col)

tensor([1., 1., 1.])
tensor([1., 1.])
tensor([1., 1.])


In [12]:
tensor_cat = torch.cat([ones_tensor,ones_tensor,ones_tensor],dim = 1)
print(tensor_cat)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
